apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingress-controller-hpa
  namespace: ingress-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress-nginx-controller
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metric:
        name: nginx_ingress_controller_requests
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: ingress-app
      target:
        type: Value
        value: 1k


